{
    "type": "error",
    "data": "Error running pipeline!",
    "stack": "Traceback (most recent call last):\n  File \"/Users/jiyoon/Library/Mobile Documents/com~apple~CloudDocs/황금토끼 GraphRAG/2025 캡스톤 프로젝트/domain_qa_system/backend/.venv/lib/python3.12/site-packages/graphrag/index/run/run_pipeline.py\", line 143, in _run_pipeline\n    result = await workflow_function(config, context)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/jiyoon/Library/Mobile Documents/com~apple~CloudDocs/황금토끼 GraphRAG/2025 캡스톤 프로젝트/domain_qa_system/backend/.venv/lib/python3.12/site-packages/graphrag/index/workflows/extract_graph.py\", line 58, in run_workflow\n    await write_table_to_storage(entities, \"entities\", context.storage)\n  File \"/Users/jiyoon/Library/Mobile Documents/com~apple~CloudDocs/황금토끼 GraphRAG/2025 캡스톤 프로젝트/domain_qa_system/backend/.venv/lib/python3.12/site-packages/graphrag/utils/storage.py\", line 34, in write_table_to_storage\n    await storage.set(f\"{name}.parquet\", table.to_parquet())\n  File \"/Users/jiyoon/Library/Mobile Documents/com~apple~CloudDocs/황금토끼 GraphRAG/2025 캡스톤 프로젝트/domain_qa_system/backend/.venv/lib/python3.12/site-packages/graphrag/storage/file_pipeline_storage.py\", line 120, in set\n    async with aiofiles.open(\n               ^^^^^^^^^^^^^^\n  File \"/Users/jiyoon/Library/Mobile Documents/com~apple~CloudDocs/황금토끼 GraphRAG/2025 캡스톤 프로젝트/domain_qa_system/backend/.venv/lib/python3.12/site-packages/aiofiles/base.py\", line 63, in __aenter__\n    return await self\n           ^^^^^^^^^^\n  File \"/Users/jiyoon/Library/Mobile Documents/com~apple~CloudDocs/황금토끼 GraphRAG/2025 캡스톤 프로젝트/domain_qa_system/backend/.venv/lib/python3.12/site-packages/aiofiles/base.py\", line 59, in __await__\n    self._obj = yield from self._coro.__await__()\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/jiyoon/Library/Mobile Documents/com~apple~CloudDocs/황금토끼 GraphRAG/2025 캡스톤 프로젝트/domain_qa_system/backend/.venv/lib/python3.12/site-packages/aiofiles/threadpool/__init__.py\", line 92, in _open\n    f = await loop.run_in_executor(executor, cb)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/concurrent/futures/thread.py\", line 59, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '/Users/jiyoon/Library/Mobile Documents/com~apple~CloudDocs/황금토끼 GraphRAG/2025 캡스톤 프로젝트/domain_qa_system/data/input2/output/entities.parquet'\n",
    "source": "[Errno 2] No such file or directory: '/Users/jiyoon/Library/Mobile Documents/com~apple~CloudDocs/황금토끼 GraphRAG/2025 캡스톤 프로젝트/domain_qa_system/data/input2/output/entities.parquet'",
    "details": null
}
